### ISSUE TITLE
Does the NAC option support reqeue message = true

### ISSUE THREAD

**Issue by eapenjohn** [ElGranLoky/node-red-contrib-amqp-ack#2]
this is just a generic question about whether the NAC option will support requeue =true

Thanks,
Eapen John

**Comment by ElGranLoky** [comment]
I do not understand very well the question.

basic.nack is {requeue=true} by default, and it does is put the message back on the message queue.

However, if you want the message to disappear basic.nack{requeue=false} just use basic.ack to remove the message from the queue.

**Comment by eapenjohn** [comment]
thanks . you answered my query
