### ISSUE TITLE
Errors sending?

### ISSUE THREAD

**Issue by paxinos** [ElGranLoky/node-red-contrib-amqp-ack#3]
Is there a way to tell if the connection is down when sending messages?  Or if there is an error sending?   

Some times the internet connection between a node-red instance and our rabbitmq server is flakey, but we don’t seem to get any error messages. And/or ability to force a reconnection.

**Comment by ElGranLoky** [comment]
1.- Once the node has been connected, the status is always connected.

If it loses the connection with rabbit, it will try to reconnect depending on whether the value of [keepalive or heartbeat](https://www.rabbitmq.com/heartbeats.html) has been set in the definition of the amqp server node.

2.- No, the [amqp-ts library](https://github.com/abreits/amqp-ts/wiki/API-Reference) does not support knowing the status of the connection, it simply tries to reconnect every so often.

The messages that have to be sent to rabbit are waiting for being asynchronous until the connection is reestablished.

You can use node-red-contrib-tcp-ping to check the status inside nodered for the amqp server and use payload.sucess to check the status.

![image](https://user-images.githubusercontent.com/2712200/103287964-16debf80-49e4-11eb-811e-923b49cb13fe.png)

But it is not necessary to do a reconnection, the node does it by itself.

**Comment by paxinos** [comment]
That is great news.  However, i just got this error running on a Mac:

1 Dec 12:50:54 - [info] [amqp-server:51dc772f.9ba648] [AMQP] Connection
status: connected

31 Dec 13:07:55 - [red] Uncaught Exception:

31 Dec 13:07:55 - Error: Heartbeat timeout

    at Heart.<anonymous>
(/Users/pax/.node-red/node_modules/amqplib/lib/connection.js:427:19)

    at emitNone (events.js:106:13)

    at Heart.emit (events.js:208:7)

    at Heart.runHeartbeat
(/Users/pax/.node-red/node_modules/amqplib/lib/heartbeat.js:88:17)

    at ontimeout (timers.js:498:11)

    at tryOnTimeout (timers.js:323:5)

    at Timer.listOnTimeout (timers.js:290:5)




*ΓΝΩΘΙ ΣΑΥΤΟΝ / **Ἐκ σκότους φῶς* / *Esse quam videri*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by ElGranLoky** [comment]
I dont have Mac.

Could you try with 1.0.9 version if have the same problem?

**Comment by paxinos** [comment]
Trying on both Mac and RasberryPi4.   Will let you know.

**Comment by paxinos** [comment]
So far we have not been able to reproduce the problem...  It happened often before.

**Comment by ElGranLoky** [comment]
Good news, I close the issue.

I have made changes in version 1.0.9 solving problems affecting stability due to a reconnection.

But the heartbeat.js problem in amqp is due to the heartbeat configuration between client and server. It can be disabled if the connection is very poor between the client and the server, but it has to be done in both.

You can also use this workarround, but only if network problems are repeated:
  https://github.com/squaremo/amqp.node/issues/557#issuecomment-606553626

Good luck.
