### ISSUE TITLE
Instructions for development environment setup

### ISSUE THREAD

**Issue by pauldeng** [ElGranLoky/node-red-contrib-amqp-ack#6]
Dear @ElGranLoky,

Thanks for the project.

I am trying to set up a development environment on Ubuntu 20.04, but I found it is quite hard for me.

I am following the Fast Developer section, but got error when
`
docker run -v ${PWD}:/src gulp
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/runner.sh": permission denied: unknown.
ERRO[0000] error waiting for container: context canceled
`

Hope you can help me with this.

Thanks.

Cheers,
Paul

**Comment by ElGranLoky** [comment]
Hi @pauldeng ,

There may be several reasons why it does not work.

1.- The command is set for windows, try using this command for linux:

docker run -v $(PWD):/src gulp

2.- The processor does not support cgroupv2 or there is a problem with the development environment.

[https://blog.hypriot.com/post/verify-kernel-container-compatibility/](https://blog.hypriot.com/post/verify-kernel-container-compatibility/)

3.- The dockerfile to generate the gulp compiler is based on mhart/alpine which only has support for amd64, and if you are using a raspberry pi or hardware arm it has no hardware support.

[https://hub.docker.com/r/mhart/alpine-node/tags?page=1&ordering=last_updated](https://hub.docker.com/r/mhart/alpine-node/tags?page=1&ordering=last_updated)

All the best,

**Comment by pauldeng** [comment]
Hi @ElGranLoky ,

Thanks for your support.

Unfortunately, I got the same error by using the Linux command you provided.
Apologize, I am not a very docker fluent guy not to mention Windows. I normally work in Ubuntu 20.04 64bit in VirtualBox.

I think more people will be able to help to build this node if you could review and update the instructions for Linux.

Cheers mate.

**Comment by ElGranLoky** [comment]
The respository is deprecated.

As an alternative you can use [@meowwolf/node-red-contrib-amqp](https://flows.nodered.org/node/@meowwolf/node-red-contrib-amqp)
