### ISSUE TITLE
amqp ack does not (n)ack when it is not in same flow with amqp in

### ISSUE THREAD

**Issue by Leemellaret** [ElGranLoky/node-red-contrib-amqp-ack#7]
Hello! Thank you for your nodes.

I have an issue. When amqp in and amqp ack nodes in same flow, they work as expected, message are acked. But if one or both of them in different flows or subflows, amqp ack node does not ack or nack messages.

How to recreate issue:
`[{"id":"e107f4db31ec8c30","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"9dc6a2662626ed9b","type":"subflow","name":"Subflow with amqp in","info":"","category":"","in":[{"x":120,"y":120,"wires":[{"id":"a2d7410788a47b76"}]}],"out":[],"env":[],"meta":{},"color":"#DDAA99"},{"id":"25bc6adaef3ad358","type":"amqp-server","host":"localhost","port":"5672","vhost":"","keepalive":"30","usetls":false,"verifyservercert":true,"useca":false,"ca":"","usetopology":false,"topology":"{\n\t\"exchanges\": [\n\t\t{\"name\": \"exchange1\", \"type\": \"direct\", \"options\": {\"durable\": false}},\n\t\t{\"name\": \"exchange2\"}\n\t],\n\t\"queues\": [\n\t\t{\"name\": \"queue1\", \"options\": {\"messageTtl\": 60000}},\n\t\t{\"name\": \"queue2\"}\n\t],\n\t\"bindings\": [\n\t\t{\"source\": \"exchange1\", \"queue\": \"queue1\", \"pattern\": \"debug\", \"args\": {}},\n\t\t{\"source\": \"exchange1\", \"exchange\": \"exchange2\", \"pattern\": \"error\"},\n\t\t{\"source\": \"exchange2\", \"queue\": \"queue2\"}\n\t]\n}","prefetch":true,"prefetchvalue":"1","prefetchack":false,"prefetchvalueack":"10"},{"id":"a2d7410788a47b76","type":"amqp ack","z":"9dc6a2662626ed9b","name":"","topic":"","iotype":"4","ioname":"NodeRED-test-queue","nack":false,"server":"25bc6adaef3ad358","x":320,"y":120,"wires":[["3acdf8e964bb7f32"]]},{"id":"3acdf8e964bb7f32","type":"debug","z":"9dc6a2662626ed9b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":530,"y":120,"wires":[]},{"id":"47990cab0f68a27a","type":"inject","z":"e107f4db31ec8c30","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payloadType":"date","x":240,"y":160,"wires":[["851d80ad05359ea2"]]},{"id":"851d80ad05359ea2","type":"amqp out","z":"e107f4db31ec8c30","name":"","routingkey":"","iotype":"4","ioname":"NodeRED-test-queue","server":"25bc6adaef3ad358","x":480,"y":160,"wires":[]},{"id":"89f85187e70aa654","type":"subflow:9dc6a2662626ed9b","z":"e107f4db31ec8c30","name":"","x":520,"y":260,"wires":[]},{"id":"e1351c6528a02527","type":"amqp in","z":"e107f4db31ec8c30","name":"","topic":"","iotype":"4","ioname":"NodeRED-test-queue","server":"25bc6adaef3ad358","x":220,"y":260,"wires":[["89f85187e70aa654"]]}]`

I think this issue is caused by using flow context in nodes.
Note: Subflow has its own flow context that differs from context of subflow as node in normal flow.

**Comment by ElGranLoky** [comment]
Correct. Indeed it is not a problem, it is how it works. 

Only one input node can be used for flow or subflow, since each in node generates a context to know the acks available in the flow or subflow.

If it is necessary to use the input of messages in several flows or subflows, you can use several input node for each. The messages can be control using rabbit routing or generating queues for each flow.
