### ISSUE TITLE
AMQP TLS Connection Issue

### ISSUE THREAD

**Issue by SudarsanDamodaran** [ElGranLoky/node-red-contrib-amqp-ack#8]
Dear ElGranLoky,

We have RabbitMQ broker with both AMQP and AMQP TLS enabled. (Please refer to the image RabbitMQ Ports).
When trying to connect from either AMQP IN or OUT node to the broker with AMQP it is working very fine. (Please refer to the image AMQP_1 and AMQP_2).
But when we are trying to connect with AMQP TLS enabled in the node with the broker it is showing connecting status only, not able to connect to the broker. (Please refer to the image AMQP_3 and AMQP_4).
Need your input.
 
Regards,
Sudarsan

<img width="445" alt="AMQP_1" src="https://github.com/ElGranLoky/node-red-contrib-amqp-ack/assets/109946775/1e2cf39f-0964-47f3-9071-a82d3fae8b45">
<img width="569" alt="AMQP_2" src="https://github.com/ElGranLoky/node-red-contrib-amqp-ack/assets/109946775/3faf2712-7c3a-4d0f-8904-f37377fa7896">
<img width="446" alt="AMQP_3" src="https://github.com/ElGranLoky/node-red-contrib-amqp-ack/assets/109946775/21c608f8-1778-4b75-93ee-d415a40b78f0">
<img width="505" alt="AMQP_4" src="https://github.com/ElGranLoky/node-red-contrib-amqp-ack/assets/109946775/e0c4ad7e-a594-41c4-b038-044cbb4b42b9">
<img width="598" alt="RabbitMQ Ports" src="https://github.com/ElGranLoky/node-red-contrib-amqp-ack/assets/109946775/2df43201-53e7-414b-bac6-58e5834c4576">

**Comment by ElGranLoky** [comment]
Sorry but the repository is deprecated.

As an alternative you can use [@meowwolf/node-red-contrib-amqp](https://flows.nodered.org/node/@meowwolf/node-red-contrib-amqp)
